name: terraform

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/workflows/terraform.yml'
  push:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - '.github/workflows/terraform.yml'
  workflow_dispatch: {}

env:
  TF_WORKING_DIR: .

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      #- name: Show OIDC claims
      #  uses: actions/github-script@v7
      #  with:
      #    script: |
      #      const idt = await core.getIDToken('sts.amazonaws.com');
      #      const claims = JSON.parse(Buffer.from(idt.split('.')[1], 'base64').toString());
      #      console.log('aud:', claims.aud);
      #      console.log('sub:', claims.sub);

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEP_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Init
        run: terraform init -input=false

      - name: Fmt
        run: terraform fmt -recursive -check

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -input=false -out=tfplan -var "aws_acc_id=${{ secrets.AWS_ACC_ID }}"

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

  apply:
    needs: plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEP_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Init
        run: terraform init -input=false

      - name: Get artifact from plan job
        uses: actions/download-artifact@v4
        with: { name: tfplan }

      - name: Apply saved plan
        run: terraform apply -input=false -auto-approve tfplan